services:
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      # Configure PostgreSQL to listen on a specific IP address
      POSTGRES_LISTEN_ADDRESSES: '172.19.0.3'
    ports:
      - "5432:5432"
    networks:
      vpcbr:
        ipv4_address: 172.19.0.3
    command: >
      postgres -c listen_addresses='172.19.0.3'
  pgadmin:
    container_name: pgadmin4_container
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - vpcbr

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

